### ISSUE TITLE
I want to know what's the metter of this

### ISSUE THREAD

**Issue by Jarrett0x** [mapozyan/caps#2]
Calibre Power Search Plugin (1, 7, 0)
Traceback (most recent call last):
  File "calibre_plugins.caps.main", line 233, in on_search
  File "calibre_plugins.caps.main", line 249, in _manage_lru
  File "site-packages\calibre\utils\config.py", line 430, in __setitem__
  File "site-packages\calibre\utils\config.py", line 372, in commit
  File "site-packages\calibre\utils\config.py", line 414, in to_raw
  File "json\__init__.py", line 251, in dumps
  File "json\encoder.py", line 209, in encode
  File "json\encoder.py", line 434, in _iterencode
  File "json\encoder.py", line 408, in _iterencode_dict
  File "json\encoder.py", line 442, in _iterencode
  File "site-packages\calibre\utils\config.py", line 393, in to_json
TypeError: PyQt5.QtCore.QByteArray('\x01\xd9\xd0\xcb\x00\x02\x00\x00\x00\x00\x01\xf1\x00\x00\x009\x00\x00\x03\xfc\x00\x00\x02i\x00\x00\x01\xf9\x00\x00\x00W\x00\x00\x03\xf4\x00\x00\x02a\x00\x00\x00\x00\x00\x00\x00\x00\x05V') is not JSON serializable

**Comment by mapozyan** [comment]
The commit mentioned above should fix this issue.

In the meantime you might go to Options dialog and click "Clear search history" button to fix it on your side.

**Comment by mapozyan** [comment]
Done.
