### ISSUE TITLE
Root certificates are missing for certificate validation

### ISSUE THREAD

**Issue by shahjinals** [mapozyan/caps#9]
I am unable to do anything with the plugin, giving the error below.

calibre, version 7.12.0
ERROR: Unhandled exception: <b>ImproperlyConfigured</b>:Root certificates are missing for certificate validation. Either pass them in using the ca_certs parameter or install certifi to use it automatically.

calibre 7.12  embedded-python: True
Windows-10-10.0.22631-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22631')
Python 3.11.5
Windows: ('10', '10.0.22631', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Amazon.com Multiple Countries (1, 0, 0) && Calibre Power Search Plugin (2, 2, 0) && Goodreads (1, 8, 2) && MultiColumnSearch (1, 0, 96) && Open With (1, 8, 3)
Traceback (most recent call last):
  File "calibre_plugins.caps.ui", line 40, in show_dialog
  File "calibre_plugins.caps.ui", line 37, in _init_dialog
  File "calibre_plugins.caps.main", line 224, in __init__
  File "calibre_plugins.caps.main", line 245, in _upgrade_to_current_version
  File "calibre_plugins.caps.main", line 319, in _get_elasticsearch_client_or_show_error
  File "calibre_plugins.caps.elasticsearch_helper", line 183, in get_elasticsearch_client
  File "calibre_plugins.caps.elasticsearch.client.__init__", line 201, in __init__
  File "calibre_plugins.caps.elasticsearch.transport", line 154, in __init__
  File "calibre_plugins.caps.elasticsearch.transport", line 212, in set_connections
  File "calibre_plugins.caps.elasticsearch.transport", line 208, in _create_connection
  File "calibre_plugins.caps.elasticsearch.connection.http_urllib3", line 187, in __init__
calibre_plugins.caps.elasticsearch.exceptions.ImproperlyConfigured: Root certificates are missing for certificate validation. Either pass them in using the ca_certs parameter or install certifi to use it automatically.

**Comment by mapozyan** [comment]
Please verify if you have properly set **xpack.security.enabled: false** in **config/elasticsearch.yml** - see corresponding section in README.
